# Country codes reference: https://www.iban.com/country-codes
- name: 'Tahnee Joyce McCoy'
  city: 'San Diego'
  country_code: 'US' # United States
  links:
    website: ''
    linkedin: 'https://www.linkedin.com/in/tj-mccoy/'
    instagram: ''
    github: ''
    logo: 'photo.jpeg'
