# Country codes reference: https://www.iban.com/country-codes
- name: 'Carmen Villalobos'
  city: 'San Diego'
  country_code: 'US' # United States
  links:
    website: ''
    linkedin: 'https://www.linkedin.com/in/carmen--villalobos/'
    instagram: ''
    github: ''
    logo: 'photo.jpg'
