# Country codes reference: https://www.iban.com/country-codes
- name: 'Leslie Pajuelo'
  city: 'Harrisburg'
  state_code: 'PA'
  country_code: 'US' # United States
  links:
    website: ''
    linkedin: 'https://www.linkedin.com/in/lesliepajuelo/'
    instagram: ''
    github: ''
    logo: 'photo.jpeg'
