# Country codes reference: https://www.iban.com/country-codes
- name: 'Carly Kennedy'
  city: 'San Diego'
  country_code: 'US' # United States
  links:
    website: 'https://carlykennedy.netlify.app/'
    linkedin: 'https://www.linkedin.com/company/women-coders-san-diego'
    instagram: ''
    github: ''
    logo: 'photo.jpeg'
