# Country codes reference: https://www.iban.com/country-codes
- name: 'Jemadean Vasquez'
  city: 'San Diego'
  state_code: 'CA' #California
  country_code: 'US' # United States
  links:
    website: ''
    linkedin: 'https://www.linkedin.com/in/jemadean-vasquez/'
    instagram: ''
    github: ''
    logo: 'photo.jpeg'
